- name: "Accessories"
  description: "Accessories"
  critical: false
  hidden: false
  selected: false
  packages:
    - cheese
    - font-manager-git
    - galculator
    - flameshot
    - liferea
    - mediainfo
    - mcomix
    - pdfarranger
    - plank
    - arcolinux-plank-themes-git
    - screenkey-git
    - variety
    - arcolinux-variety-git
    - vim-plugins
    - xfburn
- name: "Conky"
  description: "Conky and conky collection"
  critical: false
  hidden: false
  selected: false
  packages:
    - conky-lua-archers
    - arcolinux-conky-collection-git
    - yad
    - arcolinux-pipemenus-git
- name: "File Manager"
  description: "Filemanager"
  critical: false
  hidden: false
  selected: false
  packages:
    - caja
    - dolphin
    - mc
    - nautilus
    - nemo
    - nemo-fileroller
    - pcmanfm
    - ranger
    - thunar
    - thunar-archive-plugin
- name: "Fonts"
  description: "Fonts"
  critical: false
  hidden: false
  selected: false
  packages:
    - adobe-source-sans-pro-fonts
    - awesome-terminal-fonts
    - terminus-font
    - ttf-bitstream-vera
    - ttf-droid
    - ttf-fira-code
    - ttf-font-awesome
    - ttf-hack
    - ttf-inconsolata
    - ttf-liberation
    - ttf-roboto
    - ttf-ubuntu-font-family
- name: "Git"
  description: "Git"
  critical: false
  hidden: false
  selected: false
  packages:
    - gitahead-bin
    - gitg
    - gitfiend
    - gitkraken
- name: "Graphics"
  description: "Graphics"
  critical: false
  hidden: false
  selected: false
  packages:
    - blender
    - darktable
    - digikam
    - gimp
    - gpick
    - inkscape
    - krita
    - nitrogen
    - nomacs
    - pinta
    - ristretto
- name: "Fun"
  description: "Fun"
  critical: false
  hidden: false
  selected: false
  packages:
    - arcolinux-meta-fun
- name: "Password Manager"
  description: "Password manager"
  critical: false
  hidden: false
  selected: false
  packages:
    - bitwarden-bin
    - enpass-bin
    - keepassxc
    - lastpass
- name: "Privacy"
  description: "Applications that ensure your privacy"
  critical: false
  hidden: false
  selected: false
  packages:
    - tor-browser
    - tor
    - privoxy
- name: "Terminals"
  description: "Terminals"
  critical: false
  hidden: false
  selected: false
  packages:
    - alacritty
    - arcolinux-termite-themes-git
    - gnome-terminal
    - guake
    - kitty
    - konsole
    - lxterminal
    - sakura
    - terminator
    - tilix
    - tilda
    - tmux
- name: "Usb"
  description: "Usb"
  critical: false
  hidden: false
  selected: false
  packages:
    - etcher-bin
    - imagewriter
    - mintstick-git
    - woeusb
- name: "Virtualbox for Linux kernel"
  description: "Installs virtualbox for linux kernel"
  critical: false
  hidden: false
  selected: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-headers
- name: "Virtualbox for Linux-lts kernel"
  description: "Installs virtualbox for linux-lts kernel"
  critical: false
  hidden: false
  selected: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-lts-headers
    - linux-lts
- name: "Zsh"
  description: "Zsh"
  critical: false
  hidden: false
  selected: false
  packages:
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
    - oh-my-zsh-git
    - arcolinux-zsh-git
